/*
 * This file was automatically generated by EvoSuite
 * Sat May 04 05:51:03 GMT 2019
 */

package brain.ga;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import brain.ga.Genome;
import brain.ga.Population;
import brain.ga.RankSelector;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RankSelector_ESTest extends RankSelector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RankSelector rankSelector0 = new RankSelector();
      Population population0 = new Population();
      Vector<Object> vector0 = new Vector<Object>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      population0.genoms = (List) linkedList0;
      vector0.add((Object) null);
      population0.genoms = (List) vector0;
      Genome genome0 = rankSelector0.select(population0);
      assertNull(genome0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RankSelector rankSelector0 = new RankSelector();
      // Undeclared exception!
      try { 
        rankSelector0.select((Population) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brain.ga.RankSelector", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Population population0 = new Population();
      Vector<String> vector0 = new Vector<String>();
      population0.genoms = (List) vector0;
      vector0.add("UhdL%/+EI");
      RankSelector rankSelector0 = new RankSelector();
      // Undeclared exception!
      try { 
        rankSelector0.select(population0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to brain.ga.Genome
         //
         verifyException("brain.ga.Population", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Population population0 = new Population();
      RankSelector rankSelector0 = new RankSelector();
      // Undeclared exception!
      try { 
        rankSelector0.select(population0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("org.evosuite.runtime.Random", e);
      }
  }
}
