/*
 * This file was automatically generated by EvoSuite
 */

package com.hf.sfm.filter;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.hf.sfm.filter.setCharacterEncodingFilter;
import java.io.IOException;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class setCharacterEncodingFilterEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      setCharacterEncodingFilter setCharacterEncodingFilter0 = new setCharacterEncodingFilter();
      setCharacterEncodingFilter0.destroy();
  }

  @Test
  public void test1()  throws Throwable  {
      setCharacterEncodingFilter setCharacterEncodingFilter0 = new setCharacterEncodingFilter();
      // Undeclared exception!
      try {
        setCharacterEncodingFilter0.doFilter((ServletRequest) null, (ServletResponse) null, (FilterChain) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      setCharacterEncodingFilter setCharacterEncodingFilter0 = new setCharacterEncodingFilter();
      setCharacterEncodingFilter0.init((FilterConfig) null);
  }
}
