/*
 * This file was automatically generated by EvoSuite
 */

package dsachat.share;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import dsachat.share.KeyExc;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class KeyExcEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      KeyExc keyExc0 = new KeyExc(byteArray0);
      byte[] byteArray1 = keyExc0.getKey();
      assertSame(byteArray1, byteArray0);
  }
}
