/*
 * This file was automatically generated by EvoSuite
 */

package dsachat.share;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import dsachat.share.UserEvent;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class UserEventEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      UserEvent userEvent0 = new UserEvent(true, "");
      boolean boolean0 = userEvent0.isDisconnect();
      assertEquals(true, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      UserEvent userEvent0 = new UserEvent(false, (String) null);
      userEvent0.getName();
      assertEquals(false, userEvent0.isDisconnect());
  }
}
