/*
 * This file was automatically generated by EvoSuite
 */

package dsachat.share.hero;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import dsachat.share.hero.Attribute;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class AttributeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Attribute attribute0 = new Attribute("", "", 0);
      String string0 = attribute0.getName();
      assertEquals(" () :0", attribute0.toString());
      assertNotNull(string0);
      assertEquals(0, attribute0.getValue());
  }

  @Test
  public void test1()  throws Throwable  {
      Attribute attribute0 = new Attribute("yP*^.x", "yP*^.x", 287);
      String string0 = attribute0.getShortcut();
      assertNotNull(string0);
      assertEquals(287, attribute0.getValue());
      assertEquals("yP*^.x (yP*^.x) :287", attribute0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      Attribute attribute0 = new Attribute("yP*^.x", "yP*^.x", 287);
      int int0 = attribute0.getValue();
      assertEquals(287, int0);
  }

  @Test
  public void test3()  throws Throwable  {
      Attribute attribute0 = new Attribute("yP*^.x", "yP*^.x", 287);
      String string0 = attribute0.toString();
      assertNotNull(string0);
      assertEquals("yP*^.x (yP*^.x) :287", string0);
  }
}
