/*
 * This file was automatically generated by EvoSuite
 */

package dsachat.share.hero;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import dsachat.share.hero.FightValue;
import dsachat.share.hero.Weapon;
import java.util.Vector;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class FightValueEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      FightValue fightValue0 = new FightValue("", 0, 248);
      String string0 = fightValue0.getName();
      assertEquals(" AT: 0 PA: 248", fightValue0.toString());
      assertNotNull(string0);
  }

  @Test
  public void test1()  throws Throwable  {
      FightValue fightValue0 = new FightValue("", 0, 248);
      String string0 = fightValue0.toString();
      assertNotNull(string0);
      assertEquals(" AT: 0 PA: 248", string0);
  }

  @Test
  public void test2()  throws Throwable  {
      FightValue fightValue0 = new FightValue("", 0, 248);
      int int0 = fightValue0.getAttack();
      assertEquals(" AT: 0 PA: 248", fightValue0.toString());
      assertEquals(0, int0);
  }

  @Test
  public void test3()  throws Throwable  {
      FightValue fightValue0 = new FightValue("", 0, 248);
      assertEquals(0, fightValue0.getAttack());
      
      fightValue0.setAttack(1);
      assertEquals(" AT: 1 PA: 248", fightValue0.toString());
      assertEquals(1, fightValue0.getAttack());
  }

  @Test
  public void test4()  throws Throwable  {
      FightValue fightValue0 = new FightValue("=c5QhYCWoj48bapUN", 0, 1392);
      int int0 = fightValue0.getDefense();
      assertEquals("=c5QhYCWoj48bapUN AT: 0 PA: 1392", fightValue0.toString());
      assertEquals(1392, int0);
  }

  @Test
  public void test5()  throws Throwable  {
      FightValue fightValue0 = new FightValue("-.=Wk0i$", (-1288), (-1));
      Vector<Weapon> vector0 = fightValue0.getWeapons();
      assertEquals("-.=Wk0i$ AT: -1288 PA: -1", fightValue0.toString());
      assertNotNull(vector0);
  }

  @Test
  public void test6()  throws Throwable  {
      FightValue fightValue0 = new FightValue("", 0, 248);
      assertEquals(248, fightValue0.getDefense());
      
      fightValue0.setDefense(0);
      assertEquals(" AT: 0 PA: 0", fightValue0.toString());
  }
}
