/*
 * This file was automatically generated by EvoSuite
 */

package dsachat.gm;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import dsachat.gm.GmMain;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class GmMainEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GmMain gmMain0 = new GmMain();
  }
}
