/*
 * This file was automatically generated by EvoSuite
 */

package com.hf.sfm.sfmis.department.pdo;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.hf.sfm.sfmis.department.pdo.ADepartment;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ADepartmentEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ADepartment aDepartment0 = new ADepartment((String) null, (String) null);
      assertNull(aDepartment0.getIdno());
  }

  @Test
  public void test1()  throws Throwable  {
      ADepartment aDepartment0 = new ADepartment();
      aDepartment0.setMark((String) null);
      assertNull(aDepartment0.getMark());
  }

  @Test
  public void test2()  throws Throwable  {
      ADepartment aDepartment0 = new ADepartment();
      String string0 = aDepartment0.getIdno();
      assertNull(string0);
  }

  @Test
  public void test3()  throws Throwable  {
      ADepartment aDepartment0 = new ADepartment();
      String string0 = aDepartment0.getMark();
      assertNull(string0);
  }

  @Test
  public void test4()  throws Throwable  {
      ADepartment aDepartment0 = new ADepartment();
      String string0 = aDepartment0.getName();
      assertNull(string0);
  }

  @Test
  public void test5()  throws Throwable  {
      ADepartment aDepartment0 = new ADepartment();
      aDepartment0.setName((String) null);
      assertNull(aDepartment0.getName());
  }

  @Test
  public void test6()  throws Throwable  {
      ADepartment aDepartment0 = new ADepartment();
      aDepartment0.setIdno((String) null);
      assertNull(aDepartment0.getIdno());
  }
}
