/*
 * This file was automatically generated by EvoSuite
 */

package dsachat.gm.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import dsachat.gm.gui.ValueHolder;
import dsachat.share.hero.Hero;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ValueHolderEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ValueHolder valueHolder0 = new ValueHolder("", (Hero) null);
      String string0 = valueHolder0.toString();
      assertEquals("", string0);
  }
}
