/*
 * This file was automatically generated by EvoSuite
 */

package com.hf.sfm.system.pdo;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.hf.sfm.system.pdo.AWorker;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class AWorkerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      String string0 = aWorker0.getFlatid();
      assertNull(string0);
  }

  @Test
  public void test1()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      String string0 = aWorker0.getPassword();
      assertNull(string0);
  }

  @Test
  public void test2()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      aWorker0.setFlatid("");
      assertEquals("", aWorker0.getFlatid());
  }

  @Test
  public void test3()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      String string0 = aWorker0.getAccount();
      assertNull(string0);
  }

  @Test
  public void test4()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      aWorker0.setPassword("");
      assertNull(aWorker0.getIdno());
  }

  @Test
  public void test5()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      String string0 = aWorker0.getPersonid();
      assertNull(string0);
  }

  @Test
  public void test6()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      String string0 = aWorker0.getIdno();
      assertNull(string0);
  }

  @Test
  public void test7()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      aWorker0.setIdno((String) null);
      assertNull(aWorker0.getGroupid());
  }

  @Test
  public void test8()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      aWorker0.setAccount((String) null);
      assertNull(aWorker0.getState());
  }

  @Test
  public void test9()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      aWorker0.setGroupid((String) null);
      assertNull(aWorker0.getPassword());
  }

  @Test
  public void test10()  throws Throwable  {
      AWorker aWorker0 = new AWorker("cN4)XZf &dO'<", "L2E)&", "L2E)&", "cN4)XZf &dO'<", "cN4)XZf &dO'<", "cN4)XZf &dO'<");
      assertEquals("cN4)XZf &dO'<", aWorker0.getState());
      assertEquals("cN4)XZf &dO'<", aWorker0.getPersonid());
      assertEquals("L2E)&", aWorker0.getPassword());
      assertEquals("L2E)&", aWorker0.getGroupid());
      assertEquals("cN4)XZf &dO'<", aWorker0.getAccount());
      assertEquals("cN4)XZf &dO'<", aWorker0.getFlatid());
  }

  @Test
  public void test11()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      String string0 = aWorker0.getState();
      assertNull(string0);
  }

  @Test
  public void test12()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      String string0 = aWorker0.getGroupid();
      assertNull(string0);
  }

  @Test
  public void test13()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      aWorker0.setState("");
      assertNull(aWorker0.getAccount());
  }

  @Test
  public void test14()  throws Throwable  {
      AWorker aWorker0 = new AWorker();
      aWorker0.setPersonid("U\"Lk C5%`KYC$.]");
      assertNull(aWorker0.getPassword());
  }
}
