/*
 * This file was automatically generated by EvoSuite
 * Sun May 05 02:52:13 GMT 2019
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ib.client.EClientErrors;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EClientErrors_ESTest extends EClientErrors_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EClientErrors eClientErrors0 = new EClientErrors();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = new EClientErrors.CodeMsgPair(512, "");
      int int0 = eClientErrors_CodeMsgPair0.code();
      assertEquals(512, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = new EClientErrors.CodeMsgPair(512, "");
      String string0 = eClientErrors_CodeMsgPair0.msg();
      assertEquals(512, eClientErrors_CodeMsgPair0.code());
      assertNotNull(string0);
  }
}
