/*
 * This file was automatically generated by EvoSuite
 */

package com.hf.sfm.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.hf.sfm.util.BasePara;
import com.hf.sfm.util.DataSource;
import javax.servlet.http.HttpSession;
import org.directwebremoting.util.FakeHttpSession;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class DataSourceEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DataSource dataSource0 = new DataSource();
      BasePara basePara0 = new BasePara();
      // Undeclared exception!
      try {
        dataSource0.getComboData(basePara0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      DataSource dataSource0 = new DataSource();
      BasePara basePara0 = new BasePara();
      // Undeclared exception!
      try {
        dataSource0.getPlanarArrData(basePara0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      DataSource dataSource0 = new DataSource();
      BasePara basePara0 = new BasePara();
      // Undeclared exception!
      try {
        dataSource0.getGridData(basePara0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test3()  throws Throwable  {
      DataSource dataSource0 = new DataSource();
      FakeHttpSession fakeHttpSession0 = new FakeHttpSession((String) null);
      String string0 = dataSource0.getSession((HttpSession) fakeHttpSession0, (String) null);
      assertEquals("null", string0);
  }
}
