/*
 * This file was automatically generated by EvoSuite
 */

package com.hf.sfm.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.hf.sfm.util.HibernateSessionFactory;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class HibernateSessionFactoryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      HibernateSessionFactory hibernateSessionFactory0 = new HibernateSessionFactory();
      assertNotNull(hibernateSessionFactory0);
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        HibernateSessionFactory.currentSession();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test2()  throws Throwable  {
      HibernateSessionFactory.closeSession();
  }
}
