/*
 * This file was automatically generated by EvoSuite
 */

package com.hf.sfm.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.hf.sfm.util.ListRange;
import java.util.ArrayList;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ListRangeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ListRange listRange0 = new ListRange();
      listRange0.setTotalSize(0);
      assertEquals(0, listRange0.getTotalSize());
  }

  @Test
  public void test1()  throws Throwable  {
      ListRange listRange0 = new ListRange();
      int int0 = listRange0.getTotalSize();
      assertEquals(0, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      ListRange listRange0 = new ListRange();
      listRange0.setData((ArrayList<Object>) null);
      assertEquals(0, listRange0.getTotalSize());
  }

  @Test
  public void test3()  throws Throwable  {
      ListRange listRange0 = new ListRange();
      ArrayList<Object> arrayList0 = listRange0.getData();
      assertNull(arrayList0);
  }
}
