/*
 * This file was automatically generated by EvoSuite
 * Sat May 04 05:50:15 GMT 2019
 */

package brain.ga;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import brain.ga.Evaluator;
import brain.ga.GAEnumAllelesSet;
import brain.ga.Genome;
import brain.ga.Population;
import brain.ga.RankSelector;
import brain.ga.Selector;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Population_ESTest extends Population_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Population population0 = new Population();
      Vector<Genome> vector0 = new Vector<Genome>();
      RankSelector rankSelector0 = new RankSelector();
      population0.selector = (Selector) rankSelector0;
      population0.genoms = (List) vector0;
      Genome genome0 = new Genome();
      vector0.add(genome0);
      population0.selectNextGenome();
      assertEquals(4, population0.getGenomeSize());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Population population0 = new Population();
      Vector<Genome> vector0 = new Vector<Genome>();
      population0.genoms = (List) vector0;
      Genome genome0 = new Genome();
      vector0.add(genome0);
      population0.getSize();
      assertEquals(4, population0.getGenomeSize());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Population population0 = new Population();
      RankSelector rankSelector0 = new RankSelector();
      population0.selector = (Selector) rankSelector0;
      population0.getSelector();
      assertEquals(4, population0.getGenomeSize());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Population population0 = new Population();
      assertEquals(4, population0.getGenomeSize());
      
      population0.genomeSize = 0;
      int int0 = population0.getGenomeSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Population population0 = new Population();
      assertEquals(4, population0.getGenomeSize());
      
      population0.setGenomeSize((-1));
      int int0 = population0.getGenomeSize();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Population population0 = new Population();
      Vector<Genome> vector0 = new Vector<Genome>();
      population0.genoms = (List) vector0;
      vector0.add((Genome) null);
      population0.get(1);
      assertEquals(4, population0.getGenomeSize());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Population population0 = new Population();
      Vector<Genome> vector0 = new Vector<Genome>();
      population0.genoms = (List) vector0;
      Genome genome0 = new Genome();
      vector0.add(genome0);
      population0.get(1);
      assertEquals(4, population0.getGenomeSize());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Population population0 = new Population();
      Vector<Genome> vector0 = new Vector<Genome>();
      population0.genoms = (List) vector0;
      Genome genome0 = new Genome();
      vector0.add(genome0);
      // Undeclared exception!
      try { 
        population0.sort();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brain.ga.Genome", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Population population0 = new Population();
      RankSelector rankSelector0 = new RankSelector();
      population0.setSelector(rankSelector0);
      // Undeclared exception!
      try { 
        population0.selectNextGenome();
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("org.evosuite.runtime.Random", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Population population0 = new Population();
      population0.genoms = null;
      // Undeclared exception!
      try { 
        population0.getSize();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brain.ga.Population", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Population population0 = new Population();
      population0.genoms = null;
      // Undeclared exception!
      try { 
        population0.get(4);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brain.ga.Population", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Population population0 = new Population();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      population0.genoms = (List) linkedList0;
      linkedList0.add("");
      // Undeclared exception!
      try { 
        population0.get(1);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to brain.ga.Genome
         //
         verifyException("brain.ga.Population", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Population population0 = new Population();
      // Undeclared exception!
      try { 
        population0.get((-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Population population0 = new Population();
      // Undeclared exception!
      try { 
        population0.get(1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Population population0 = new Population();
      Vector<Object> vector0 = new Vector<Object>();
      population0.genoms = (List) vector0;
      Object object0 = new Object();
      vector0.add(object0);
      // Undeclared exception!
      try { 
        population0.sort();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to brain.ga.Genome
         //
         verifyException("brain.ga.Population", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Population population0 = new Population();
      population0.sort();
      assertEquals(4, population0.getGenomeSize());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Population population0 = new Population();
      RankSelector rankSelector0 = new RankSelector();
      population0.selector = (Selector) rankSelector0;
      Vector<Integer> vector0 = new Vector<Integer>();
      population0.genoms = (List) vector0;
      Integer integer0 = new Integer((-2090));
      vector0.add(integer0);
      // Undeclared exception!
      try { 
        population0.selectNextGenome();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Integer cannot be cast to brain.ga.Genome
         //
         verifyException("brain.ga.Population", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Population population0 = new Population();
      population0.getSize();
      assertEquals(4, population0.getGenomeSize());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Population population0 = new Population();
      population0.setEvaluator((Evaluator) null);
      assertEquals(4, population0.getGenomeSize());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Population population0 = new Population();
      // Undeclared exception!
      try { 
        population0.selectNextGenome();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brain.ga.Population", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Population population0 = new Population();
      population0.getEvaluator();
      assertEquals(4, population0.getGenomeSize());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Population population0 = new Population();
      population0.getSelector();
      assertEquals(4, population0.getGenomeSize());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Population population0 = new Population();
      GAEnumAllelesSet gAEnumAllelesSet0 = new GAEnumAllelesSet();
      population0.initialize(gAEnumAllelesSet0);
      assertEquals(4, population0.getGenomeSize());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Population population0 = new Population();
      int int0 = population0.getGenomeSize();
      assertEquals(4, int0);
  }
}
