/*
 * This file was automatically generated by EvoSuite
 */

package com.hf.sfm.system.business;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.hf.sfm.system.business.MenuManage;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class MenuManageEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      MenuManage menuManage0 = new MenuManage();
      assertNotNull(menuManage0);
  }
}
