/*
 * This file was automatically generated by EvoSuite
 * Sun May 05 03:14:26 GMT 2019
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ib.client.ComboLeg;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComboLeg_ESTest extends ComboLeg_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      comboLeg0.m_designatedLocation = "_X@_R[hyRYRf;zW3%";
      ComboLeg comboLeg1 = new ComboLeg();
      comboLeg1.equals(comboLeg0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg();
      comboLeg1.m_exchange = "com.ib.client.Util";
      comboLeg0.equals(comboLeg1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      comboLeg0.m_action = "hc";
      ComboLeg comboLeg1 = new ComboLeg(0, 0, (String) null, "com.ib.client.ComboLeg", 0, 0, "hc");
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertEquals(0, comboLeg1.m_openClose);
      assertFalse(boolean0);
      assertEquals(0, comboLeg1.m_ratio);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg();
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      
      comboLeg1.m_shortSaleSlot = 1;
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg(0, 0, "cv't|~ERDjv6", "cv't|~ERDjv6", 0, (-3748), "com.ib.client.ComboLeg");
      assertEquals(0, comboLeg1.m_openClose);
      
      comboLeg1.m_openClose = 3370;
      boolean boolean0 = comboLeg1.equals(comboLeg0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      assertEquals(0, comboLeg0.m_conId);
      
      comboLeg0.m_conId = 3;
      ComboLeg comboLeg1 = new ComboLeg();
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg(1076, 1603, "", "", 2294, (-657), "");
      ComboLeg comboLeg1 = new ComboLeg(1076, (-657), "v=)\"ku", "v=)\"ku", (-657), 0, "");
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertEquals(1076, comboLeg1.m_conId);
      assertEquals((-657), comboLeg0.m_shortSaleSlot);
      assertEquals(2294, comboLeg0.m_openClose);
      assertFalse(boolean0);
      assertEquals(1603, comboLeg0.m_ratio);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      boolean boolean0 = comboLeg0.equals(comboLeg0);
      assertEquals(0, comboLeg0.m_shortSaleSlot);
      assertEquals(0, comboLeg0.m_ratio);
      assertTrue(boolean0);
      assertEquals(0, comboLeg0.m_openClose);
      assertEquals(0, comboLeg0.m_conId);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      comboLeg0.m_designatedLocation = "_X@_R[hyRYRf;zW3%";
      ComboLeg comboLeg1 = new ComboLeg();
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      assertEquals(0, comboLeg1.m_openClose);
      assertEquals(0, comboLeg1.m_conId);
      assertFalse(boolean0);
      assertFalse(comboLeg1.equals((Object)comboLeg0));
      assertEquals(0, comboLeg1.m_ratio);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg();
      assertTrue(comboLeg1.equals((Object)comboLeg0));
      
      comboLeg0.m_exchange = "S&";
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertFalse(comboLeg1.equals((Object)comboLeg0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg(0, 0, "gs;`R&>a]", "H9fOibvj", 0, 0, "");
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertEquals(0, comboLeg1.m_openClose);
      assertEquals(0, comboLeg1.m_ratio);
      assertEquals(0, comboLeg1.m_conId);
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg();
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      
      comboLeg1.m_shortSaleSlot = 1;
      boolean boolean0 = comboLeg1.equals(comboLeg0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg();
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      assertEquals(0, comboLeg1.m_ratio);
      assertEquals(0, comboLeg1.m_conId);
      assertEquals(0, comboLeg1.m_openClose);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg(0, 2, "v", (String) null, 0);
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      assertEquals(0, comboLeg1.m_openClose);
      assertEquals(0, comboLeg1.m_conId);
      assertFalse(boolean0);
      assertEquals(0, comboLeg0.m_ratio);
      assertEquals(2, comboLeg1.m_ratio);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg(1, 3, (String) null, (String) null, 0, 0, "com.ib.client.ComboLeg");
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertEquals(0, comboLeg0.m_ratio);
      assertEquals(1, comboLeg1.m_conId);
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      assertFalse(boolean0);
      assertEquals(0, comboLeg1.m_openClose);
      assertEquals(0, comboLeg0.m_conId);
      assertEquals(3, comboLeg1.m_ratio);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      boolean boolean0 = comboLeg0.equals((Object) null);
      assertEquals(0, comboLeg0.m_shortSaleSlot);
      assertEquals(0, comboLeg0.m_ratio);
      assertEquals(0, comboLeg0.m_conId);
      assertEquals(0, comboLeg0.m_openClose);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        comboLeg0.equals(object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to com.ib.client.ComboLeg
         //
         verifyException("com.ib.client.ComboLeg", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg(0, 0, (String) null, "aZC&ZvY/ *-|a]V", 3, 3, "aZC&ZvY/ *-|a]V");
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertEquals(3, comboLeg1.m_openClose);
      assertEquals(3, comboLeg1.m_shortSaleSlot);
      assertFalse(boolean0);
      assertEquals(0, comboLeg1.m_conId);
      assertEquals(0, comboLeg1.m_ratio);
  }
}
