/*
 * This file was automatically generated by EvoSuite
 */


import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import java.sql.SQLException;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class DataBaseEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DataBase dataBase0 = null;
      try {
        dataBase0 = new DataBase("0bkEXFG'O|Kj.{0l8.", "0bkEXFG'O|Kj.{0l8.", "0bkEXFG'O|Kj.{0l8.", "0bkEXFG'O|Kj.{0l8.");
        fail("Expecting exception: ClassNotFoundException");
      } catch(ClassNotFoundException e) {
        /*
         * Class 'org/postgresql/Driver.class' should be in target project, but could not be found!
         */
      }
  }
}
