/*
 * This file was automatically generated by EvoSuite
 * Sun May 05 02:52:05 GMT 2019
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ib.client.ContractDetails;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ContractDetails_ESTest extends ContractDetails_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ContractDetails contractDetails0 = new ContractDetails();
      ContractDetails contractDetails1 = new ContractDetails(contractDetails0.m_summary, (String) null, (String) null, 0, (String) null, (String) null, (-285), (String) null, (String) null, "", (String) null, "lII4mOH'-Sp2K", "(ho`mY3khK.t;NUY%", "^]y", (String) null);
      assertEquals(0, contractDetails0.m_underConId);
  }
}
