/*
 * This file was automatically generated by EvoSuite
 */

package dsachat.server;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import dsachat.server.Entry;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class EntryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Entry entry0 = new Entry();
  }
}
