/*
 * This file was automatically generated by EvoSuite
 */

package dsachat.server;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import dsachat.server.ServerMain;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class ServerMainEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ServerMain serverMain0 = new ServerMain();
  }
}
