/*
 * This file was automatically generated by EvoSuite
 * Sun May 05 03:14:53 GMT 2019
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ib.client.TagValue;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TagValue_ESTest extends TagValue_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TagValue tagValue0 = new TagValue("8qMV@ 3 `^_w\u0002w", "|: {_YAdT/YMnbR");
      TagValue tagValue1 = new TagValue("8qMV@ 3 `^_w\u0002w", "8qMV@ 3 `^_w\u0002w");
      boolean boolean0 = tagValue0.equals(tagValue1);
      assertFalse(tagValue1.equals((Object)tagValue0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TagValue tagValue0 = new TagValue("j-n", "*z.]+W");
      TagValue tagValue1 = new TagValue();
      boolean boolean0 = tagValue0.equals(tagValue1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TagValue tagValue0 = new TagValue();
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        tagValue0.equals(object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to com.ib.client.TagValue
         //
         verifyException("com.ib.client.TagValue", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TagValue tagValue0 = new TagValue();
      TagValue tagValue1 = new TagValue("", "com.ib.client.TagValue");
      assertFalse(tagValue1.equals((Object)tagValue0));
      
      tagValue0.m_value = "com.ib.client.TagValue";
      boolean boolean0 = tagValue1.equals(tagValue0);
      assertTrue(tagValue1.equals((Object)tagValue0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TagValue tagValue0 = new TagValue();
      TagValue tagValue1 = new TagValue("5Vm|~F4Bp6nKg#iLn", (String) null);
      boolean boolean0 = tagValue0.equals(tagValue1);
      assertFalse(tagValue1.equals((Object)tagValue0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TagValue tagValue0 = new TagValue();
      boolean boolean0 = tagValue0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TagValue tagValue0 = new TagValue();
      boolean boolean0 = tagValue0.equals(tagValue0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TagValue tagValue0 = new TagValue();
      TagValue tagValue1 = new TagValue("", "com.ib.client.TagValue");
      boolean boolean0 = tagValue0.equals(tagValue1);
      assertFalse(boolean0);
      assertFalse(tagValue1.equals((Object)tagValue0));
  }
}
