/*
 * This file was automatically generated by EvoSuite
 */

package com.hf.sfm.sfmis.personinfo.pdo;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.hf.sfm.sfmis.personinfo.pdo.APersonInfo;
import java.util.Date;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class APersonInfoEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo("wJ$KMDik<;z", "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", "wJ$KMDik<;z", "wJ$KMDik<;z");
      aPersonInfo0.setDepartment("wJ$KMDik<;z");
      assertEquals("wJ$KMDik<;z", aPersonInfo0.getReason());
  }

  @Test
  public void test1()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      aPersonInfo0.setPersontype((String) null);
      assertNull(aPersonInfo0.getWbm());
  }

  @Test
  public void test2()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      String string0 = aPersonInfo0.getSex();
      assertNull(string0);
  }

  @Test
  public void test3()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo("wJ$KMDik<;z", "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", "wJ$KMDik<;z", "wJ$KMDik<;z");
      aPersonInfo0.setBirthday((Date) null);
      assertEquals("wJ$KMDik<;z", aPersonInfo0.getReason());
  }

  @Test
  public void test4()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo("wJ$KMDik<;z", "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", "wJ$KMDik<;z", "wJ$KMDik<;z");
      String string0 = aPersonInfo0.getDepartment();
      assertEquals("wJ$KMDik<;z", string0);
  }

  @Test
  public void test5()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      aPersonInfo0.setMobile("");
      assertNull(aPersonInfo0.getDepartment());
  }

  @Test
  public void test6()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      String string0 = aPersonInfo0.getPersonid();
      assertNull(string0);
  }

  @Test
  public void test7()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo("wJ$KMDik<;z", "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", "wJ$KMDik<;z", "wJ$KMDik<;z");
      Date date0 = new Date();
      aPersonInfo0.setIndate(date0);
      assertEquals(1372718651037L, date0.getTime());
  }

  @Test
  public void test8()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      String string0 = aPersonInfo0.getWbm();
      assertNull(string0);
  }

  @Test
  public void test9()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo("wJ$KMDik<;z", "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", "wJ$KMDik<;z", "wJ$KMDik<;z");
      String string0 = aPersonInfo0.getName();
      assertEquals("wJ$KMDik<;z", string0);
  }

  @Test
  public void test10()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      Date date0 = aPersonInfo0.getOutdate();
      assertNull(date0);
  }

  @Test
  public void test11()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      aPersonInfo0.setName("");
      assertEquals("", aPersonInfo0.getName());
  }

  @Test
  public void test12()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo("wJ$KMDik<;z", "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", "wJ$KMDik<;z", "wJ$KMDik<;z");
      String string0 = aPersonInfo0.getPersontype();
      assertEquals("wJ$KMDik<;z", string0);
  }

  @Test
  public void test13()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo("wJ$KMDik<;z", "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", "wJ$KMDik<;z", "wJ$KMDik<;z");
      aPersonInfo0.setOutdate((Date) null);
      assertEquals("wJ$KMDik<;z", aPersonInfo0.getSex());
  }

  @Test
  public void test14()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      String string0 = aPersonInfo0.getReason();
      assertNull(string0);
  }

  @Test
  public void test15()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      Date date0 = aPersonInfo0.getIndate();
      assertNull(date0);
  }

  @Test
  public void test16()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      String string0 = aPersonInfo0.getPym();
      assertNull(string0);
  }

  @Test
  public void test17()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      aPersonInfo0.setWbm("");
      assertNull(aPersonInfo0.getPersontype());
  }

  @Test
  public void test18()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      String string0 = aPersonInfo0.getMobile();
      assertNull(string0);
  }

  @Test
  public void test19()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      aPersonInfo0.setPym((String) null);
      assertNull(aPersonInfo0.getPersonid());
  }

  @Test
  public void test20()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      aPersonInfo0.setPersonid("tQwmULL|_c'}");
      assertNull(aPersonInfo0.getPersontype());
  }

  @Test
  public void test21()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      aPersonInfo0.setSex((String) null);
      assertNull(aPersonInfo0.getMobile());
  }

  @Test
  public void test22()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo();
      Date date0 = aPersonInfo0.getBirthday();
      assertNull(date0);
  }

  @Test
  public void test23()  throws Throwable  {
      APersonInfo aPersonInfo0 = new APersonInfo("wJ$KMDik<;z", "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", (Date) null, "wJ$KMDik<;z", "wJ$KMDik<;z", "wJ$KMDik<;z");
      aPersonInfo0.setReason("wJ$KMDik<;z");
      assertNull(aPersonInfo0.getMobile());
  }
}
