/*
 * This file was automatically generated by EvoSuite
 */

package com.ib.client;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.ib.client.EClientErrors;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class EClientErrorsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = EClientErrors.FAIL_SEND_CANMKT;
      String string0 = eClientErrors_CodeMsgPair0.msg();
      assertEquals("Cancel Market Data Sending Error - ", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = new EClientErrors.CodeMsgPair((-353), "The TWS is out of date and must be upgraded.");
      assertEquals((-353), eClientErrors_CodeMsgPair0.m_errorCode);
  }

  @Test
  public void test2()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = EClientErrors.FAIL_SEND_SERVER_LOG_LEVEL;
      int int0 = eClientErrors_CodeMsgPair0.code();
      assertEquals(521, int0);
  }

  @Test
  public void test3()  throws Throwable  {
      EClientErrors eClientErrors0 = new EClientErrors();
      assertNotNull(eClientErrors0);
  }
}
