/*
 * This file was automatically generated by EvoSuite
 */

package com.ib.client;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.ib.client.OrderState;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class OrderStateEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState((String) null, (String) null, (String) null, (String) null, 0.0, 0.0, 0.0, (String) null, (String) null);
      boolean boolean0 = orderState0.equals((Object) orderState1);
      assertEquals(true, boolean0);
  }

  @Test
  public void test1()  throws Throwable  {
      OrderState orderState0 = new OrderState("", "", "", "", 500.1158817614033, 500.1158817614033, 500.1158817614033, "", "");
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals((Object) orderState1);
      assertEquals(500.1158817614033, orderState0.m_commission, 0.01D);
      assertEquals(500.1158817614033, orderState0.m_maxCommission, 0.01D);
      assertEquals(false, boolean0);
      assertEquals(500.1158817614033, orderState0.m_minCommission, 0.01D);
  }

  @Test
  public void test2()  throws Throwable  {
      OrderState orderState0 = new OrderState("", "", "", "", 500.1158817614033, 500.1158817614033, 500.1158817614033, "", "");
      boolean boolean0 = orderState0.equals((Object) orderState0);
      assertEquals(500.1158817614033, orderState0.m_minCommission, 0.01D);
      assertEquals(true, boolean0);
      assertEquals(500.1158817614033, orderState0.m_maxCommission, 0.01D);
      assertEquals(500.1158817614033, orderState0.m_commission, 0.01D);
  }

  @Test
  public void test3()  throws Throwable  {
      OrderState orderState0 = new OrderState(")p-#T9Ln", "|<EiV", "|<EiV", (String) null, 8.796307208177932, (-1.0), 8.796307208177932, ")p-#T9Ln", ")p-#T9Ln");
      boolean boolean0 = orderState0.equals((Object) null);
      assertEquals(false, boolean0);
      assertEquals(8.796307208177932, orderState0.m_commission, 0.01D);
      assertEquals(8.796307208177932, orderState0.m_maxCommission, 0.01D);
      assertEquals((-1.0), orderState0.m_minCommission, 0.01D);
  }

  @Test
  public void test4()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState((String) null, (String) null, (String) null, (String) null, 0.0, (-1.0), 0.0, (String) null, (String) null);
      boolean boolean0 = orderState0.equals((Object) orderState1);
      assertEquals(0.0, orderState0.m_minCommission, 0.01D);
      assertFalse(orderState1.equals(orderState0));
      assertEquals(false, boolean0);
      assertEquals(0.0, orderState1.m_maxCommission, 0.01D);
      assertEquals(0.0, orderState1.m_commission, 0.01D);
  }

  @Test
  public void test5()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState((String) null, (String) null, (String) null, (String) null, 0.0, 0.0, 1291.8648080794296, (String) null, (String) null);
      boolean boolean0 = orderState0.equals((Object) orderState1);
      assertFalse(orderState1.equals(orderState0));
      assertEquals(0.0, orderState1.m_minCommission, 0.01D);
      assertEquals(0.0, orderState1.m_commission, 0.01D);
      assertEquals(false, boolean0);
      assertEquals(0.0, orderState0.m_maxCommission, 0.01D);
  }

  @Test
  public void test6()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      orderState0.m_status = "e5PN]!n`F";
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals((Object) orderState1);
      assertEquals(0.0, orderState0.m_minCommission, 0.01D);
      assertEquals(0.0, orderState0.m_maxCommission, 0.01D);
      assertEquals(false, boolean0);
      assertFalse(orderState1.equals(orderState0));
  }

  @Test
  public void test7()  throws Throwable  {
      OrderState orderState0 = new OrderState("=/vON.wd_y,KpXQ2", "=/vON.wd_y,KpXQ2", "=/vON.wd_y,KpXQ2", "", 0.0, 0.0, 0.0, "", "");
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals((Object) orderState1);
      assertEquals(false, boolean0);
      assertEquals(0.0, orderState1.m_maxCommission, 0.01D);
      assertEquals(0.0, orderState1.m_commission, 0.01D);
      assertEquals(0.0, orderState1.m_minCommission, 0.01D);
  }

  @Test
  public void test8()  throws Throwable  {
      OrderState orderState0 = new OrderState("=/vON.wd_y,KpXQ2", "=/vON.wd_y,KpXQ2", "=/vON.wd_y,KpXQ2", "", 0.0, 0.0, 0.0, "", "");
      OrderState orderState1 = new OrderState("", "=/vON.wd_y,KpXQ2", "c_{A/Ie%l1P<K?", "C8GET>]2,?r(qdq>+", 0.0, 0.0, 0.0, (String) null, (String) null);
      boolean boolean0 = orderState0.equals((Object) orderState1);
      assertEquals(0.0, orderState0.m_minCommission, 0.01D);
      assertEquals(0.0, orderState0.m_commission, 0.01D);
      assertEquals(false, boolean0);
      assertEquals(0.0, orderState0.m_maxCommission, 0.01D);
  }

  @Test
  public void test9()  throws Throwable  {
      OrderState orderState0 = new OrderState(")p-#T9Ln", (String) null, (String) null, ")p-#T9Ln", 0.0, 0.0, 0.0, "|<EiV", (String) null);
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals((Object) orderState1);
      assertEquals(0.0, orderState0.m_maxCommission, 0.01D);
      assertEquals(false, boolean0);
  }

  @Test
  public void test10()  throws Throwable  {
      OrderState orderState0 = new OrderState("=/vON.wd_y,KpXQ2", "=/vON.wd_y,KpXQ2", "=/vON.wd_y,KpXQ2", "=/vON.wd_y,KpXQ2", 0.0, 0.0, 0.0, "=/vON.wd_y,KpXQ2", "=/vON.wd_y,KpXQ2");
      OrderState orderState1 = new OrderState("=/vON.wd_y,KpXQ2", "=/vON.wd_y,KpXQ2", "=/vON.wd_y,KpXQ2", "=/vON.wd_y,KpXQ2", 0.0, 0.0, 0.0, "", "=/vON.wd_y,KpXQ2");
      boolean boolean0 = orderState0.equals((Object) orderState1);
      assertEquals(false, boolean0);
      assertFalse(orderState1.equals(orderState0));
  }
}
