/*
 * This file was automatically generated by EvoSuite
 */

package com.hf.sfm.sfmis.personinfo.business;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.hf.sfm.sfmis.personinfo.business.PersonInfoMgr;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class PersonInfoMgrEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      PersonInfoMgr personInfoMgr0 = new PersonInfoMgr();
      assertNotNull(personInfoMgr0);
  }
}
