/*
 * This file was automatically generated by EvoSuite
 */

package brain.ga;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import brain.ga.Evaluator;
import brain.ga.GAAlgorithm;
import brain.ga.Mutator;
import brain.ga.Selector;
import brain.ga.SexualCrossover;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class GAAlgorithmEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      GAAlgorithm gAAlgorithm0 = new GAAlgorithm();
      SexualCrossover sexualCrossover0 = gAAlgorithm0.getCrossoverOperator();
      assertNull(sexualCrossover0);
  }

  @Test
  public void test1()  throws Throwable  {
      GAAlgorithm gAAlgorithm0 = new GAAlgorithm();
      Evaluator evaluator0 = gAAlgorithm0.getEvaluator();
      assertNull(evaluator0);
  }

  @Test
  public void test2()  throws Throwable  {
      GAAlgorithm gAAlgorithm0 = new GAAlgorithm();
      gAAlgorithm0.evolve();
      assertEquals(true, gAAlgorithm0.done());
  }

  @Test
  public void test3()  throws Throwable  {
      GAAlgorithm gAAlgorithm0 = new GAAlgorithm();
      gAAlgorithm0.step();
      assertEquals(true, gAAlgorithm0.done());
  }

  @Test
  public void test4()  throws Throwable  {
      GAAlgorithm gAAlgorithm0 = new GAAlgorithm();
      gAAlgorithm0.setMutator((Mutator) null);
      assertEquals(true, gAAlgorithm0.done());
  }

  @Test
  public void test5()  throws Throwable  {
      GAAlgorithm gAAlgorithm0 = new GAAlgorithm();
      // Undeclared exception!
      try {
        gAAlgorithm0.setSelector((Selector) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test6()  throws Throwable  {
      GAAlgorithm gAAlgorithm0 = new GAAlgorithm();
      Mutator mutator0 = gAAlgorithm0.getMutator();
      assertNull(mutator0);
  }

  @Test
  public void test7()  throws Throwable  {
      GAAlgorithm gAAlgorithm0 = new GAAlgorithm();
      gAAlgorithm0.setCrossoverOperator((SexualCrossover) null);
      assertEquals(true, gAAlgorithm0.done());
  }

  @Test
  public void test8()  throws Throwable  {
      GAAlgorithm gAAlgorithm0 = new GAAlgorithm();
      Selector selector0 = gAAlgorithm0.getSelector();
      assertNull(selector0);
  }

  @Test
  public void test9()  throws Throwable  {
      GAAlgorithm gAAlgorithm0 = new GAAlgorithm();
      // Undeclared exception!
      try {
        gAAlgorithm0.setEvaluator((Evaluator) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
