/*
 * This file was automatically generated by EvoSuite
 */

package brain.ga;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import brain.ga.Population;
import brain.ga.RankSelector;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class RankSelectorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      RankSelector rankSelector0 = new RankSelector();
      Population population0 = new Population();
      // Undeclared exception!
      try {
        rankSelector0.select(population0);
        fail("Expecting exception: ArithmeticException");
      } catch(ArithmeticException e) {
        /*
         * / by zero
         */
      }
  }
}
