/*
 * This file was automatically generated by EvoSuite
 */

package brain.ga;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import brain.ga.VectorAllelesGenome;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class VectorAllelesGenomeEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      VectorAllelesGenome vectorAllelesGenome0 = new VectorAllelesGenome();
  }
}
